CREATE TABLE institute_employees
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_security_number BIGINT REFERENCES research_associate ON DELETE CASCADE,
    institute_id           BIGINT REFERENCES institute (id) ON DELETE CASCADE
);