CREATE TABLE project_participation
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_security_number BIGINT REFERENCES research_associate ON DELETE CASCADE,
    project_id             BIGINT REFERENCES project (id) ON DELETE CASCADE,
    hours                  INTEGER NOT NULL
);