CREATE TABLE faculty
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        VARCHAR(100) NOT NULL,
    dean_social_security_number BIGINT
);